---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.0
  name: configurations.chainsaw.kyverno.io
spec:
  group: chainsaw.kyverno.io
  names:
    kind: Configuration
    listKind: ConfigurationList
    plural: configurations
    singular: configuration
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Configuration is the resource that contains the configuration
          used to run tests.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Configuration spec.
            properties:
              excludeTestRegex:
                description: ExcludeTestRegex is used to exclude tests based on a
                  regular expression.
                type: string
              failFast:
                description: FailFast determines whether the test should stop upon
                  encountering the first failure.
                type: boolean
              fullName:
                description: FullName makes use of the full test case folder path
                  instead of the folder name.
                type: boolean
              includeTestRegex:
                description: IncludeTestRegex is used to include tests based on a
                  regular expression.
                type: string
              namespace:
                description: Namespace defines the namespace to use for tests.
                type: string
              parallel:
                default: 8
                description: The maximum number of tests to run at once.
                format: int
                type: integer
              repeatCount:
                default: 1
                description: RepeatCount indicates how many times the tests should
                  be executed.
                format: int
                minimum: 1
                type: integer
              reportFormat:
                description: ReportFormat determines test report format (JSON|XML|nil)
                  nil == no report. maps to report.Type, however we don't want generated.deepcopy
                  to have reference to it.
                enum:
                - JSON
                - XML
                type: string
              reportName:
                default: chainsaw-report
                description: ReportName defines the name of report to create. It defaults
                  to "chainsaw-report".
                type: string
              skipDelete:
                description: If set, do not delete the resources after running the
                  tests (implies SkipClusterDelete).
                type: boolean
              suppress:
                description: Suppress is used to suppress logs.
                items:
                  type: string
                type: array
              testDirs:
                description: Directories containing test cases to run.
                items:
                  type: string
                type: array
              timeout:
                default: 30s
                description: Timeout per test step.
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
