INHERIT: ./mkdocs.base.yaml

nav:
- Home: index.md
- Getting started:
  - quick-start/index.md
  - quick-start/install.md
  - quick-start/completion.md
  - quick-start/first-test.md
  - quick-start/run-tests.md
  - quick-start/assertion-trees.md
  - quick-start/bindings.md
  - quick-start/resource-templating.md
  - quick-start/operation-outputs.md
  - quick-start/try-catch.md
  - quick-start/timeouts.md
  - quick-start/cleanup.md
  - quick-start/next-steps.md
  - quick-start/resources.md
  - CI/CD:
    - cicd/gh-action.md
- Configuration:
  - configuration/index.md
  - configuration/file.md
  - configuration/flags.md
  - Options:
    - configuration/options/timeouts.md
    - configuration/options/discovery.md
    - configuration/options/execution.md
    - configuration/options/namespace.md
    - configuration/options/templating.md
    - configuration/options/cleanup.md
    - configuration/options/deletion.md
    - configuration/options/error.md
    - configuration/options/report.md
    - configuration/options/clusters.md
    - configuration/options/pause.md
    - configuration/options/no-cluster.md
    - configuration/options/label-selectors.md
    - configuration/options/values.md
    - configuration/options/sharding.md
    - configuration/options/yaml-anchors.md
- Test:
  - test/index.md
  - test/explicit.md
  - test/conventional.md
  - General concepts:
    - general/inheritance.md
    - general/namespace.md
    - general/bindings.md
    - general/templating.md
    - general/outputs.md
    - general/references.md
    - general/scenarios.md
    - general/checks.md
  - Test spec:
    - test/spec/index.md
  - Test step spec:
    - step/index.md
    - step/try.md
    - step/catch.md
    - step/finally.md
    - step/cleanup.md
- Operations:
  - operations/index.md
  - operations/apply.md
  - operations/assert.md
  - operations/command.md
  - operations/create.md
  - operations/delete.md
  - operations/error.md
  - operations/patch.md
  - operations/script.md
  - operations/sleep.md
  - operations/update.md
  - Kubectl helpers:
    - operations/helpers/index.md
    - operations/helpers/describe.md
    - operations/helpers/events.md
    - operations/helpers/get.md
    - operations/helpers/logs.md
    - operations/helpers/wait.md
- Reference:
  - reference/index.md
  - reference/builtins.md
  - reference/json-schemas.md
  - APIs:
    - v1alpha1: reference/apis/chainsaw.v1alpha1.md
    - v1alpha2: reference/apis/chainsaw.v1alpha2.md
  - JMESPath:
    - Functions: reference/jp/functions.md
    - Examples:
      - reference/jp/examples/abs.md
      - reference/jp/examples/add.md
      - reference/jp/examples/as_string.md
      - reference/jp/examples/at.md
      - reference/jp/examples/avg.md
      - reference/jp/examples/base64_decode.md
      - reference/jp/examples/base64_encode.md
      - reference/jp/examples/ceil.md
      - reference/jp/examples/compare.md
      - reference/jp/examples/concat.md
      - reference/jp/examples/contains.md
      - reference/jp/examples/divide.md
      - reference/jp/examples/ends_with.md
      - reference/jp/examples/env.md
      - reference/jp/examples/equal_fold.md
      - reference/jp/examples/find_first.md
      - reference/jp/examples/find_last.md
      - reference/jp/examples/floor.md
      - reference/jp/examples/from_items.md
      - reference/jp/examples/group_by.md
      - reference/jp/examples/items.md
      - reference/jp/examples/join.md
      - reference/jp/examples/json_parse.md
      - reference/jp/examples/keys.md
      - reference/jp/examples/label_match.md
      - reference/jp/examples/length.md
      - reference/jp/examples/lookup.md
      - reference/jp/examples/lower.md
      - reference/jp/examples/map.md
      - reference/jp/examples/max.md
      - reference/jp/examples/max_by.md
      - reference/jp/examples/merge.md
      - reference/jp/examples/min.md
      - reference/jp/examples/min_by.md
      - reference/jp/examples/modulo.md
      - reference/jp/examples/multiply.md
      - reference/jp/examples/not_null.md
      - reference/jp/examples/object_from_lists.md
      - reference/jp/examples/pad_left.md
      - reference/jp/examples/pad_right.md
      - reference/jp/examples/parse_json.md
      - reference/jp/examples/parse_yaml.md
      - reference/jp/examples/path_canonicalize.md
      - reference/jp/examples/pattern_match.md
      - reference/jp/examples/random.md
      - reference/jp/examples/regex_match.md
      - reference/jp/examples/regex_replace_all.md
      - reference/jp/examples/regex_replace_all_literal.md
      - reference/jp/examples/replace.md
      - reference/jp/examples/replace_all.md
      - reference/jp/examples/reverse.md
      - reference/jp/examples/round.md
      - reference/jp/examples/semver_compare.md
      - reference/jp/examples/sort.md
      - reference/jp/examples/sort_by.md
      - reference/jp/examples/split.md
      - reference/jp/examples/starts_with.md
      - reference/jp/examples/subtract.md
      - reference/jp/examples/sum.md
      - reference/jp/examples/time_add.md
      - reference/jp/examples/time_after.md
      - reference/jp/examples/time_before.md
      - reference/jp/examples/time_between.md
      - reference/jp/examples/time_diff.md
      - reference/jp/examples/time_now.md
      - reference/jp/examples/time_now_utc.md
      - reference/jp/examples/time_parse.md
      - reference/jp/examples/time_since.md
      - reference/jp/examples/time_to_cron.md
      - reference/jp/examples/time_truncate.md
      - reference/jp/examples/time_utc.md
      - reference/jp/examples/to_array.md
      - reference/jp/examples/to_boolean.md
      - reference/jp/examples/to_lower.md
      - reference/jp/examples/to_number.md
      - reference/jp/examples/to_string.md
      - reference/jp/examples/to_upper.md
      - reference/jp/examples/trim.md
      - reference/jp/examples/trim_left.md
      - reference/jp/examples/trim_prefix.md
      - reference/jp/examples/trim_right.md
      - reference/jp/examples/trim_space.md
      - reference/jp/examples/truncate.md
      - reference/jp/examples/type.md
      - reference/jp/examples/upper.md
      - reference/jp/examples/values.md
      - reference/jp/examples/wildcard.md
      - reference/jp/examples/x509_decode.md
      - reference/jp/examples/x_k8s_exists.md
      - reference/jp/examples/x_k8s_get.md
      - reference/jp/examples/x_k8s_list.md
      - reference/jp/examples/x_k8s_resource_exists.md
      - reference/jp/examples/x_k8s_server_version.md
      - reference/jp/examples/x_metrics_decode.md
      - reference/jp/examples/zip.md
  - Command Line:
    - chainsaw: reference/commands/chainsaw.md
    - chainsaw assert: reference/commands/chainsaw_assert.md
    - chainsaw build: reference/commands/chainsaw_build.md
    - chainsaw build docs: reference/commands/chainsaw_build_docs.md
    - chainsaw completion: reference/commands/chainsaw_completion.md
    - chainsaw completion bash: reference/commands/chainsaw_completion_bash.md
    - chainsaw completion fish: reference/commands/chainsaw_completion_fish.md
    - chainsaw completion powershell: reference/commands/chainsaw_completion_powershell.md
    - chainsaw completion zsh: reference/commands/chainsaw_completion_zsh.md
    - chainsaw create: reference/commands/chainsaw_create.md
    - chainsaw create test: reference/commands/chainsaw_create_test.md
    - chainsaw docs: reference/commands/chainsaw_docs.md
    - chainsaw export: reference/commands/chainsaw_export.md
    - chainsaw export schemas: reference/commands/chainsaw_export_schemas.md
    - chainsaw lint: reference/commands/chainsaw_lint.md
    - chainsaw migrate: reference/commands/chainsaw_migrate.md
    - chainsaw migrate kuttl: reference/commands/chainsaw_migrate_kuttl.md
    - chainsaw migrate kuttl config: reference/commands/chainsaw_migrate_kuttl_config.md
    - chainsaw migrate kuttl tests: reference/commands/chainsaw_migrate_kuttl_tests.md
    - chainsaw renovate: reference/commands/chainsaw_renovate.md
    - chainsaw renovate config: reference/commands/chainsaw_renovate_config.md
    - chainsaw test: reference/commands/chainsaw_test.md
    - chainsaw version: reference/commands/chainsaw_version.md
- Examples:
  - examples/index.md
  - examples/crds.md
  - examples/events.md
  - examples/label-selectors.md
  - examples/inline.md
  - examples/concurrency.md
  - examples/kube-version.md
  - examples/non-resource-assertions.md
  - examples/values.md
  - examples/multi-cluster.md
  - examples/negative-testing.md
  - examples/test-output.md
  - Guides:
    - guides/lint.md
    - guides/kuttl-migration.md
    - guides/test-docs.md
- Community: 
  - community/index.md
  - Contributing: community/contribute.md
  - Reporting a bug: community/reporting-a-bug.md
  - Reporting a docs issue: community/reporting-a-docs-issue.md
  - Requesting a change: community/requesting-a-change.md
  - Making a pull request: community/making-a-pull-request.md
