INHERIT: ./mkdocs.base.yaml

nav:
- Home: index.md
- Getting started:
  - quick-start/index.md
  - quick-start/install.md
  - quick-start/completion.md
  - quick-start/first-test.md
  - quick-start/run-tests.md
  - quick-start/assertion-trees.md
  - quick-start/bindings.md
  - quick-start/resource-templating.md
  - quick-start/operation-outputs.md
  - quick-start/try-catch.md
  - quick-start/timeouts.md
  - quick-start/cleanup.md
  - quick-start/next-steps.md
  - Advanced use cases:
    - quick-start/advanced/index.md
    - quick-start/advanced/inline.md
    - quick-start/advanced/negative-testing.md
    - quick-start/advanced/crds.md
    - quick-start/advanced/events.md
    - quick-start/advanced/concurrency.md
    - quick-start/advanced/kube-version.md
    - quick-start/advanced/non-resource-assertions.md
    - quick-start/advanced/test-output.md
    - quick-start/advanced/label-selectors.md
    - quick-start/advanced/values.md
    - quick-start/advanced/multi-cluster.md
  - gh-action.md
- Configuration:
  - configuration/index.md
  - configuration/file.md
  - configuration/flags.md
  - Options:
    - configuration/options/timeouts.md
    - configuration/options/discovery.md
    - configuration/options/execution.md
    - configuration/options/namespace.md
    - configuration/options/templating.md
    - configuration/options/cleanup.md
    - configuration/options/deletion.md
    - configuration/options/error.md
    - configuration/options/report.md
    - configuration/options/clusters.md
    - configuration/options/pause.md
    - configuration/options/no-cluster.md
- Test:
  - tests/index.md
  - Test definition:
    - tests/definition/index.md
    - tests/definition/explicit.md
    - tests/definition/conventional.md
  - General concepts:
    - tests/general/inheritance.md
    - tests/general/bindings.md
    - tests/general/templating.md
    - tests/general/namespace.md
  - Test spec:
    - tests/spec/index.md
    - tests/general/outputs.md
  - Steps spec:
    - steps/index.md
    - steps/try.md
    - steps/catch.md
    - steps/finally.md
    - Operations:
      - operations/index.md
      - operations/check.md
      - operations/apply.md
      - operations/assert.md
      - operations/create.md
      - operations/command.md
      - operations/delete.md
      - operations/error.md
      - operations/patch.md
      - operations/script.md
      - operations/sleep.md
      - operations/update.md
      - operations/wait.md
      - operations/templating.md
      - operations/non-resource-assert.md
    - Collectors:
      - collectors/index.md
      - collectors/pod-logs.md
      - collectors/events.md
      - collectors/get.md
      - collectors/describe.md
- Writing tests:
  - Other resources:
    - more/lint.md
    - more/test-docs.md
- Reference:
  - reference/bindings.md
  - reference/json-schemas.md
  - APIs:
    - v1alpha1: reference/apis/chainsaw.v1alpha1.md
    - v1alpha2: reference/apis/chainsaw.v1alpha2.md
  - JMESPath:
    - Functions: reference/jp/functions.md
  - Command Line:
    - chainsaw: reference/commands/chainsaw.md
    - chainsaw assert: reference/commands/chainsaw_assert.md
    - chainsaw build: reference/commands/chainsaw_build.md
    - chainsaw build docs: reference/commands/chainsaw_build_docs.md
    - chainsaw completion: reference/commands/chainsaw_completion.md
    - chainsaw completion bash: reference/commands/chainsaw_completion_bash.md
    - chainsaw completion fish: reference/commands/chainsaw_completion_fish.md
    - chainsaw completion powershell: reference/commands/chainsaw_completion_powershell.md
    - chainsaw completion zsh: reference/commands/chainsaw_completion_zsh.md
    - chainsaw create: reference/commands/chainsaw_create.md
    - chainsaw create test: reference/commands/chainsaw_create_test.md
    - chainsaw docs: reference/commands/chainsaw_docs.md
    - chainsaw export: reference/commands/chainsaw_export.md
    - chainsaw export schemas: reference/commands/chainsaw_export_schemas.md
    - chainsaw lint: reference/commands/chainsaw_lint.md
    - chainsaw migrate: reference/commands/chainsaw_migrate.md
    - chainsaw migrate kuttl: reference/commands/chainsaw_migrate_kuttl.md
    - chainsaw migrate kuttl config: reference/commands/chainsaw_migrate_kuttl_config.md
    - chainsaw migrate kuttl tests: reference/commands/chainsaw_migrate_kuttl_tests.md
    - chainsaw test: reference/commands/chainsaw_test.md
    - chainsaw version: reference/commands/chainsaw_version.md
- Community: community/index.md
